"""
Seed data for journal templates — formatting specifications per publisher.
"""
from typing import List, Dict, Any

JOURNAL_TEMPLATES_SEED: List[Dict[str, Any]] = [
    {
        "journal_name": "IEEE Transactions Template",
        "publisher": "IEEE",
        "latex_template": "ieee",
        "citation_style": "ieee",
        "formatting_rules": {
            "paper_size": "US letter",
            "font_family": "Times New Roman",
            "font_size": 10,
            "line_spacing": 1.0,
            "column_count": 2,
            "margin_top": "0.75in",
            "margin_bottom": "1in",
            "margin_left_cm": 1.9,
            "margin_right_cm": 1.9,
            "title_case": "upper_and_lower",
        },
        "section_order": [
            "title", "abstract", "introduction", "methodology",
            "results", "discussion", "conclusion",
            "acknowledgments", "references", "appendices",
        ],
        "word_limits": {
            "abstract": 200,
            "introduction": 800,
            "methodology": 2000,
            "results": 2000,
            "discussion": 2000,
            "conclusion": 500,
        },
        "figure_specs": {
            "dpi": 300,
            "formats": ["eps", "pdf", "png"],
            "color_mode": "CMYK",
            "caption_position": "below",
            "label_format": "Fig. {number}.",
        },
        "reference_specs": {
            "max_refs": 60,
            "doi_required": True,
            "numbered": True,
            "bracket_style": "square",
            "sort_order": "appearance",
        },
        "reference_format": "[{number}] {authors}, \"{title},\" {journal}, vol. {volume}, no. {number}, pp. {pages}, {year}.",
    },
    {
        "journal_name": "Elsevier Journal Template",
        "publisher": "Elsevier",
        "latex_template": "elsevier",
        "citation_style": "apa",
        "formatting_rules": {
            "paper_size": "A4",
            "font_family": "Times New Roman",
            "font_size": 12,
            "line_spacing": 2.0,
            "column_count": 1,
            "margin_top": "2.54cm",
            "margin_bottom": "2.54cm",
            "margin_left_cm": 2.54,
            "margin_right_cm": 2.54,
            "title_case": "sentence",
        },
        "section_order": [
            "title", "abstract", "keywords", "introduction",
            "methods", "results", "discussion", "conclusion",
            "acknowledgments", "references", "appendices",
        ],
        "word_limits": {
            "abstract": 250,
        },
        "figure_specs": {
            "dpi": 300,
            "formats": ["tiff", "eps", "pdf"],
            "color_mode": "CMYK",
            "caption_position": "below",
            "label_format": "Fig. {number}.",
        },
        "reference_specs": {
            "max_refs": None,
            "doi_required": True,
            "numbered": False,
            "bracket_style": "round",
            "sort_order": "alphabetical",
        },
        "reference_format": "{authors} ({year}). {title}. {journal}, {volume}({issue}), {pages}. https://doi.org/{doi}",
    },
    {
        "journal_name": "Springer Journal Template",
        "publisher": "Springer",
        "latex_template": "springer",
        "citation_style": "vancouver",
        "formatting_rules": {
            "paper_size": "A4",
            "font_family": "Times New Roman",
            "font_size": 10,
            "line_spacing": 1.5,
            "column_count": 2,
            "margin_top": "2cm",
            "margin_bottom": "2cm",
            "margin_left_cm": 2.0,
            "margin_right_cm": 2.0,
            "title_case": "upper_and_lower",
        },
        "section_order": [
            "title", "abstract", "keywords", "introduction",
            "materials and methods", "results", "discussion",
            "conclusion", "acknowledgments", "references",
        ],
        "word_limits": {
            "abstract": 250,
        },
        "figure_specs": {
            "dpi": 300,
            "formats": ["tiff", "eps", "jpeg"],
            "color_mode": "RGB",
            "caption_position": "below",
            "label_format": "Fig. {number}",
        },
        "reference_specs": {
            "max_refs": None,
            "doi_required": True,
            "numbered": True,
            "bracket_style": "square",
            "sort_order": "appearance",
        },
        "reference_format": "{number}. {authors}. {title}. {journal}. {year};{volume}({issue}):{pages}.",
    },
    {
        "journal_name": "Nature Journal Template",
        "publisher": "Nature",
        "latex_template": "nature",
        "citation_style": "nature",
        "formatting_rules": {
            "paper_size": "A4",
            "font_family": "Times New Roman",
            "font_size": 11,
            "line_spacing": 2.0,
            "column_count": 2,
            "margin_top": "2cm",
            "margin_bottom": "2cm",
            "margin_left_cm": 2.0,
            "margin_right_cm": 2.0,
            "title_case": "sentence",
        },
        "section_order": [
            "title", "abstract", "introduction", "results",
            "discussion", "methods", "data availability",
            "acknowledgments", "references",
        ],
        "word_limits": {
            "abstract": 150,
            "introduction": 500,
        },
        "figure_specs": {
            "dpi": 300,
            "formats": ["eps", "pdf", "tiff"],
            "color_mode": "CMYK",
            "caption_position": "below",
            "label_format": "Figure {number}",
        },
        "reference_specs": {
            "max_refs": 50,
            "doi_required": True,
            "numbered": True,
            "bracket_style": "superscript",
            "sort_order": "appearance",
        },
        "reference_format": "{number}. {authors}. {title}. {journal} {volume}, {pages} ({year}).",
    },
]
