"""
Seed data for the Academic Phrasebank — 200+ curated sentence templates.
Categorized by section and function_tag, based on the Manchester Academic
Phrasebank taxonomy. Each entry has a template with {slots} that users fill in.
"""
from typing import List, Dict, Any

PHRASEBANK_SEED: List[Dict[str, Any]] = [
    # ================================================================
    # INTRODUCTION — Establishing the territory / importance (7)
    # ================================================================
    {
        "section": "introduction", "function_tag": "establishing_importance",
        "sub_function": "claiming_centrality",
        "template_text": "{topic} plays a crucial role in {field}, with significant implications for {application_area}.",
        "slots": {"topic": {"type": "text", "required": True, "hint": "your research topic"},
                  "field": {"type": "text", "required": True, "hint": "the broader field"},
                  "application_area": {"type": "text", "required": True, "hint": "area where this matters"}},
        "example_filled": "Machine learning plays a crucial role in medical diagnostics, with significant implications for early cancer detection.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "establishing_importance",
        "sub_function": "claiming_centrality",
        "template_text": "In recent years, there has been growing interest in {topic}, driven by {motivation}.",
        "slots": {"topic": {"type": "text", "required": True, "hint": "research topic"},
                  "motivation": {"type": "text", "required": True, "hint": "what's driving this interest"}},
        "example_filled": "In recent years, there has been growing interest in renewable energy storage, driven by the urgent need for sustainable power solutions.",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "establishing_importance",
        "sub_function": "claiming_centrality",
        "template_text": "{topic} has emerged as a {adjective} area of research within {field}.",
        "slots": {"topic": {"type": "text", "required": True, "hint": "your topic"},
                  "adjective": {"type": "select", "required": True, "options": ["promising", "critical", "rapidly evolving", "controversial", "under-explored"]},
                  "field": {"type": "text", "required": True, "hint": "academic field"}},
        "example_filled": "Quantum computing has emerged as a rapidly evolving area of research within computer science.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "establishing_importance",
        "sub_function": "citing_statistics",
        "template_text": "Recent estimates suggest that {phenomenon} affects approximately {percentage}% of {population}, representing a significant {domain} burden.",
        "slots": {"phenomenon": {"type": "text", "required": True, "hint": "the phenomenon being measured"},
                  "percentage": {"type": "number", "required": True, "hint": "estimated prevalence percentage"},
                  "population": {"type": "text", "required": True, "hint": "target population"},
                  "domain": {"type": "select", "required": True, "options": ["economic", "public health", "social", "environmental"]}},
        "example_filled": "Recent estimates suggest that postpartum depression affects approximately 15% of new mothers, representing a significant public health burden.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "establishing_importance",
        "sub_function": "highlighting_trend",
        "template_text": "The prevalence of {phenomenon} has increased {adverb} over the past {time_period}, with {consequence}.",
        "slots": {"phenomenon": {"type": "text", "required": True, "hint": "phenomenon under study"},
                  "adverb": {"type": "select", "required": True, "options": ["dramatically", "steadily", "substantially", "moderately"]},
                  "time_period": {"type": "text", "required": True, "hint": "e.g., decade, 20 years"},
                  "consequence": {"type": "text", "required": True, "hint": "main consequence"}},
        "example_filled": "The prevalence of childhood obesity has increased dramatically over the past two decades, with profound implications for long-term population health.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "establishing_importance",
        "sub_function": "policy_relevance",
        "template_text": "Understanding {topic} is essential for informing {policy_area} and guiding {stakeholder} decision-making.",
        "slots": {"topic": {"type": "text", "required": True, "hint": "research topic"},
                  "policy_area": {"type": "text", "required": True, "hint": "relevant policy domain"},
                  "stakeholder": {"type": "text", "required": True, "hint": "who needs this knowledge"}},
        "example_filled": "Understanding climate adaptation behaviors is essential for informing environmental policy and guiding municipal planning decision-making.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "establishing_importance",
        "sub_function": "theoretical_significance",
        "template_text": "From a theoretical perspective, {topic} provides a unique opportunity to test {theory} under {condition} conditions.",
        "slots": {"topic": {"type": "text", "required": True, "hint": "your research topic"},
                  "theory": {"type": "text", "required": True, "hint": "the theoretical framework"},
                  "condition": {"type": "select", "required": True, "options": ["naturalistic", "controlled", "ecologically valid", "field"]}},
        "example_filled": "From a theoretical perspective, social media communication provides a unique opportunity to test social identity theory under naturalistic conditions.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # INTRODUCTION — Identifying a gap / problem (9)
    # ================================================================
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "highlighting_problem",
        "template_text": "Despite considerable research on {existing_work}, {gap_description} remains poorly understood.",
        "slots": {"existing_work": {"type": "text", "required": True, "hint": "what has been studied"},
                  "gap_description": {"type": "text", "required": True, "hint": "what we still don't know"}},
        "example_filled": "Despite considerable research on antibiotic resistance mechanisms, the role of environmental factors in resistance gene transfer remains poorly understood.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "highlighting_problem",
        "template_text": "A key limitation of previous studies is that they {limitation}, which raises questions about {implication}.",
        "slots": {"limitation": {"type": "text", "required": True, "hint": "what previous studies failed to address"},
                  "implication": {"type": "text", "required": True, "hint": "why this limitation matters"}},
        "example_filled": "A key limitation of previous studies is that they relied exclusively on self-reported data, which raises questions about measurement accuracy.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "highlighting_problem",
        "template_text": "To date, no study has systematically examined {phenomenon} in the context of {context}.",
        "slots": {"phenomenon": {"type": "text", "required": True, "hint": "the unstudied phenomenon"},
                  "context": {"type": "text", "required": True, "hint": "the setting or population"}},
        "example_filled": "To date, no study has systematically examined the long-term effects of microplastic exposure in the context of human pregnancy outcomes.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "contradictory_evidence",
        "template_text": "The evidence regarding {topic} is {contradiction_type}. While some studies suggest that {finding_a}, others report that {finding_b}.",
        "slots": {"topic": {"type": "text", "required": True, "hint": "the debated topic"},
                  "contradiction_type": {"type": "select", "required": True, "options": ["inconclusive", "contradictory", "mixed", "limited"]},
                  "finding_a": {"type": "text", "required": True, "hint": "what one side found"},
                  "finding_b": {"type": "text", "required": True, "hint": "what the other side found"}},
        "example_filled": "The evidence regarding the effectiveness of cognitive behavioral therapy for chronic pain is inconclusive. While some studies suggest that it significantly reduces pain intensity, others report that its effects are comparable to placebo.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "methodological_gap",
        "template_text": "Most prior work in this area has relied on {method_type}, which may not adequately capture {aspect}. There is a need for studies employing {alternative_method}.",
        "slots": {"method_type": {"type": "select", "required": True, "options": ["cross-sectional designs", "self-report measures", "laboratory experiments", "small convenience samples", "qualitative approaches"]},
                  "aspect": {"type": "text", "required": True, "hint": "what was not adequately captured"},
                  "alternative_method": {"type": "text", "required": True, "hint": "better methodological approach"}},
        "example_filled": "Most prior work in this area has relied on cross-sectional designs, which may not adequately capture developmental trajectories. There is a need for studies employing longitudinal methods.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "population_gap",
        "template_text": "Findings from {population_a} may not generalize to {population_b} due to differences in {factor}.",
        "slots": {"population_a": {"type": "text", "required": True, "hint": "studied population"},
                  "population_b": {"type": "text", "required": True, "hint": "understudied population"},
                  "factor": {"type": "text", "required": True, "hint": "key differentiating factor"}},
        "example_filled": "Findings from Western university students may not generalize to community-dwelling older adults due to differences in life experience and cognitive reserve.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "temporal_gap",
        "template_text": "While {topic} has been extensively studied in {period_a}, relatively little is known about its {aspect} in {period_b}.",
        "slots": {"topic": {"type": "text", "required": True, "hint": "research topic"},
                  "period_a": {"type": "text", "required": True, "hint": "well-studied time/context"},
                  "aspect": {"type": "text", "required": True, "hint": "which aspect is understudied"},
                  "period_b": {"type": "text", "required": True, "hint": "understudied time/context"}},
        "example_filled": "While consumer behavior has been extensively studied in brick-and-mortar retail contexts, relatively little is known about its dynamics in virtual reality shopping environments.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "scale_gap",
        "template_text": "Previous research has primarily examined {phenomenon} at the {scale_a} level, leaving questions about its manifestation at the {scale_b} level unanswered.",
        "slots": {"phenomenon": {"type": "text", "required": True, "hint": "phenomenon under study"},
                  "scale_a": {"type": "select", "required": True, "options": ["individual", "group", "organizational", "regional", "national"]},
                  "scale_b": {"type": "select", "required": True, "options": ["individual", "group", "organizational", "regional", "national", "global"]}},
        "example_filled": "Previous research has primarily examined organizational resilience at the firm level, leaving questions about its manifestation at the supply chain network level unanswered.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "identifying_gap",
        "sub_function": "practical_gap",
        "template_text": "There is a disconnect between {theoretical_area} and {practical_area}, limiting the translational impact of current research.",
        "slots": {"theoretical_area": {"type": "text", "required": True, "hint": "theoretical research domain"},
                  "practical_area": {"type": "text", "required": True, "hint": "practical application domain"}},
        "example_filled": "There is a disconnect between machine learning research and clinical workflow requirements, limiting the translational impact of current algorithmic advances.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # INTRODUCTION — Stating purpose / objectives (8)
    # ================================================================
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "research_aim",
        "template_text": "The aim of this {study_type} is to {action} {target} in order to {purpose}.",
        "slots": {"study_type": {"type": "select", "required": True, "options": ["study", "investigation", "research", "randomized controlled trial", "systematic review"]},
                  "action": {"type": "select", "required": True, "options": ["examine", "investigate", "evaluate", "compare", "determine", "characterize"]},
                  "target": {"type": "text", "required": True, "hint": "what you are studying"},
                  "purpose": {"type": "text", "required": True, "hint": "the broader purpose"}},
        "example_filled": "The aim of this study is to investigate the effects of sleep deprivation on cognitive performance in order to inform clinical guidelines for shift workers.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "research_aim",
        "template_text": "We sought to {action} whether {hypothesis_or_question}.",
        "slots": {"action": {"type": "select", "required": True, "options": ["determine", "test", "investigate", "establish", "clarify"]},
                  "hypothesis_or_question": {"type": "text", "required": True, "hint": "what you want to find out"}},
        "example_filled": "We sought to determine whether early intervention improves long-term outcomes in patients with mild cognitive impairment.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "hypothesis",
        "template_text": "We hypothesized that {variable_a} would be {direction} associated with {variable_b}, after controlling for {covariates}.",
        "slots": {"variable_a": {"type": "text", "required": True, "hint": "independent variable"},
                  "direction": {"type": "select", "required": True, "options": ["positively", "negatively", "significantly"]},
                  "variable_b": {"type": "text", "required": True, "hint": "dependent variable"},
                  "covariates": {"type": "text", "required": True, "hint": "control variables"}},
        "example_filled": "We hypothesized that physical activity would be positively associated with mental well-being, after controlling for age, gender, and socioeconomic status.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "research_question",
        "template_text": "This study addresses the following research question: {question}?",
        "slots": {"question": {"type": "text", "required": True, "hint": "your core research question (ending with ?)"}},
        "example_filled": "This study addresses the following research question: To what extent does social media usage moderate the relationship between loneliness and academic performance?",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "multiple_objectives",
        "template_text": "Specifically, this study has {number} objectives: (1) to {objective_a}; (2) to {objective_b}; and (3) to {objective_c}.",
        "slots": {"number": {"type": "select", "required": True, "options": ["three", "two"]},
                  "objective_a": {"type": "text", "required": True, "hint": "first objective"},
                  "objective_b": {"type": "text", "required": True, "hint": "second objective"},
                  "objective_c": {"type": "text", "required": False, "hint": "third objective"}},
        "example_filled": "Specifically, this study has three objectives: (1) to quantify the prevalence of burnout among nurses; (2) to identify key workplace predictors; and (3) to evaluate the moderating role of social support.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "contribution_statement",
        "template_text": "This paper makes {number} contributions to the literature: ({label_a}) {contribution_a}, and ({label_b}) {contribution_b}.",
        "slots": {"number": {"type": "select", "required": True, "options": ["two", "three"]},
                  "label_a": {"type": "select", "required": True, "options": ["i", "a", "1"]},
                  "contribution_a": {"type": "text", "required": True, "hint": "first contribution"},
                  "label_b": {"type": "select", "required": True, "options": ["ii", "b", "2"]},
                  "contribution_b": {"type": "text", "required": True, "hint": "second contribution"}},
        "example_filled": "This paper makes two contributions to the literature: (i) a novel theoretical framework integrating resilience and digital transformation, and (ii) empirical evidence from a multi-industry sample.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "scope_delimitation",
        "template_text": "It is important to note that this study focuses specifically on {focus_area}, rather than {excluded_area}.",
        "slots": {"focus_area": {"type": "text", "required": True, "hint": "what this study covers"},
                  "excluded_area": {"type": "text", "required": True, "hint": "what is intentionally excluded"}},
        "example_filled": "It is important to note that this study focuses specifically on acute care hospital settings, rather than primary care or long-term care facilities.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "stating_purpose",
        "sub_function": "novelty_claim",
        "template_text": "To the best of our knowledge, this is the first study to {novel_action} using {approach}.",
        "slots": {"novel_action": {"type": "text", "required": True, "hint": "what makes this study new"},
                  "approach": {"type": "text", "required": True, "hint": "the methodological approach"}},
        "example_filled": "To the best of our knowledge, this is the first study to simultaneously model customer satisfaction and employee engagement using dyadic longitudinal data.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # INTRODUCTION — Outlining structure (4)
    # ================================================================
    {
        "section": "introduction", "function_tag": "outlining_structure",
        "sub_function": "paper_structure",
        "template_text": "The remainder of this paper is structured as follows. Section {section_num_a} describes {content_a}. Section {section_num_b} presents {content_b}. Finally, Section {section_num_c} discusses {content_c}.",
        "slots": {"section_num_a": {"type": "text", "required": True, "hint": "section number (e.g., 2)"},
                  "content_a": {"type": "text", "required": True, "hint": "what this section covers"},
                  "section_num_b": {"type": "text", "required": True, "hint": "section number (e.g., 3)"},
                  "content_b": {"type": "text", "required": True, "hint": "what this section covers"},
                  "section_num_c": {"type": "text", "required": True, "hint": "section number (e.g., 4)"},
                  "content_c": {"type": "text", "required": True, "hint": "what the final section covers"}},
        "example_filled": "The remainder of this paper is structured as follows. Section 2 describes the experimental methodology. Section 3 presents the main findings. Finally, Section 4 discusses the implications and limitations of this work.",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "outlining_structure",
        "sub_function": "concise_overview",
        "template_text": "Following this introduction, we describe our {approach} in Section {method_section}, report our findings in Section {results_section}, and discuss their implications in Section {discussion_section}.",
        "slots": {"approach": {"type": "select", "required": True, "options": ["methodology", "experimental setup", "analytical framework", "research design"]},
                  "method_section": {"type": "text", "required": True, "hint": "section number for methods"},
                  "results_section": {"type": "text", "required": True, "hint": "section number for results"},
                  "discussion_section": {"type": "text", "required": True, "hint": "section number for discussion"}},
        "example_filled": "Following this introduction, we describe our experimental setup in Section 2, report our findings in Section 3, and discuss their implications in Section 4.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "outlining_structure",
        "sub_function": "detailed_outline",
        "template_text": "The paper proceeds as follows. {section_a} introduces {topic_a}. {section_b} details {topic_b}. {section_c} empirically tests {topic_c}. Finally, {section_d} concludes with {topic_d}.",
        "slots": {"section_a": {"type": "text", "required": True, "hint": "e.g., Section 2"},
                  "topic_a": {"type": "text", "required": True, "hint": "what section introduces"},
                  "section_b": {"type": "text", "required": True, "hint": "e.g., Section 3"},
                  "topic_b": {"type": "text", "required": True, "hint": "what section details"},
                  "section_c": {"type": "text", "required": True, "hint": "e.g., Section 4"},
                  "topic_c": {"type": "text", "required": True, "hint": "what section tests"},
                  "section_d": {"type": "text", "required": True, "hint": "e.g., Section 5"},
                  "topic_d": {"type": "text", "required": True, "hint": "what section concludes with"}},
        "example_filled": "The paper proceeds as follows. Section 2 introduces the institutional background. Section 3 details our data and identification strategy. Section 4 empirically tests the main hypotheses. Finally, Section 5 concludes with policy implications.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "introduction", "function_tag": "outlining_structure",
        "sub_function": "simple_end",
        "template_text": "We begin by reviewing the relevant literature, then describe our {method_approach}, present our results, and conclude with a discussion of their implications.",
        "slots": {"method_approach": {"type": "select", "required": True, "options": ["methodological approach", "experimental design", "data and empirical strategy", "analytical framework"]}},
        "example_filled": "We begin by reviewing the relevant literature, then describe our data and empirical strategy, present our results, and conclude with a discussion of their implications.",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # METHODS — Describing experimental design (7)
    # ================================================================
    {
        "section": "methods", "function_tag": "describing_design",
        "sub_function": "study_design",
        "template_text": "A {design_type} design was employed to {purpose}. Participants were recruited from {recruitment_source} between {start_date} and {end_date}.",
        "slots": {"design_type": {"type": "select", "required": True, "options": ["cross-sectional", "longitudinal", "randomized controlled", "quasi-experimental", "mixed-methods"]},
                  "purpose": {"type": "text", "required": True, "hint": "what the design enables"},
                  "recruitment_source": {"type": "text", "required": True, "hint": "where participants came from"},
                  "start_date": {"type": "text", "required": True, "hint": "start of period"},
                  "end_date": {"type": "text", "required": True, "hint": "end of period"}},
        "example_filled": "A cross-sectional design was employed to examine the prevalence of burnout among healthcare workers. Participants were recruited from three major hospitals between January 2024 and June 2024.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "describing_design",
        "sub_function": "participants",
        "template_text": "A total of {n} participants ({male_percent}% male; mean age = {mean_age} ± {sd_age} years) were included in the final analysis.",
        "slots": {"n": {"type": "number", "required": True, "hint": "total sample size"},
                  "male_percent": {"type": "number", "required": False, "hint": "percentage male"},
                  "mean_age": {"type": "number", "required": False, "hint": "mean age"},
                  "sd_age": {"type": "number", "required": False, "hint": "SD of age"}},
        "example_filled": "A total of 342 participants (48.5% male; mean age = 34.2 ± 8.7 years) were included in the final analysis.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "describing_design",
        "sub_function": "inclusion_exclusion",
        "template_text": "Inclusion criteria were: {criteria_in}. Exclusion criteria were: {criteria_ex}.",
        "slots": {"criteria_in": {"type": "text", "required": True, "hint": "list inclusion criteria"},
                  "criteria_ex": {"type": "text", "required": True, "hint": "list exclusion criteria"}},
        "example_filled": "Inclusion criteria were: age ≥ 18 years, diagnosis of type 2 diabetes, and ability to provide informed consent. Exclusion criteria were: pregnancy, severe renal impairment (eGFR < 30), and current participation in another clinical trial.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "describing_design",
        "sub_function": "sample_size_justification",
        "template_text": "An a priori power analysis using {software} indicated that a minimum sample size of {n} was required to detect a {effect_size} effect ({test_type}, α = {alpha}, power = {power}).",
        "slots": {"software": {"type": "select", "required": True, "options": ["G*Power", "R (pwr package)", "PASS", "STATA"]},
                  "n": {"type": "number", "required": True, "hint": "required sample size"},
                  "effect_size": {"type": "select", "required": True, "options": ["small (d = 0.2)", "medium (d = 0.5)", "large (d = 0.8)"]},
                  "test_type": {"type": "select", "required": True, "options": ["independent t-test", "paired t-test", "ANOVA", "chi-square test", "correlation"]},
                  "alpha": {"type": "number", "required": True, "hint": "significance level (usually 0.05)"},
                  "power": {"type": "number", "required": True, "hint": "statistical power (usually 0.80 or 0.90)"}},
        "example_filled": "An a priori power analysis using G*Power indicated that a minimum sample size of 128 was required to detect a medium (d = 0.5) effect (independent t-test, α = 0.05, power = 0.80).",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "describing_design",
        "sub_function": "randomization",
        "template_text": "Participants were randomly allocated to either the {group_a} group (n = {n_a}) or the {group_b} group (n = {n_b}) using {method}, ensuring {allocation_property}.",
        "slots": {"group_a": {"type": "text", "required": True, "hint": "name of intervention/treatment group"},
                  "n_a": {"type": "number", "required": True, "hint": "size of group A"},
                  "group_b": {"type": "text", "required": True, "hint": "name of control group"},
                  "n_b": {"type": "number", "required": True, "hint": "size of group B"},
                  "method": {"type": "select", "required": True, "options": ["computer-generated block randomization", "stratified randomization", "simple randomization via sealed envelopes"]},
                  "allocation_property": {"type": "select", "required": True, "options": ["concealment of allocation", "balanced group sizes", "equal representation of strata"]}},
        "example_filled": "Participants were randomly allocated to either the mindfulness training group (n = 64) or the waitlist control group (n = 64) using computer-generated block randomization, ensuring concealment of allocation.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "describing_design",
        "sub_function": "blinding",
        "template_text": "To minimize bias, {blinding_type} was maintained. Specifically, {detail}.",
        "slots": {"blinding_type": {"type": "select", "required": True, "options": ["double-blinding", "single-blinding", "triple-blinding"]},
                  "detail": {"type": "text", "required": True, "hint": "who was blinded and how"}},
        "example_filled": "To minimize bias, double-blinding was maintained. Specifically, neither the participants nor the outcome assessors were aware of group assignments until after data analysis was complete.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "describing_design",
        "sub_function": "comparative_design",
        "template_text": "To assess {outcome}, we compared {comparison_groups} across {conditions_or_timepoints}.",
        "slots": {"outcome": {"type": "text", "required": True, "hint": "what was compared"},
                  "comparison_groups": {"type": "text", "required": True, "hint": "groups being compared"},
                  "conditions_or_timepoints": {"type": "text", "required": True, "hint": "conditions or time points"}},
        "example_filled": "To assess treatment efficacy, we compared the intervention and control groups across three time points (baseline, post-treatment, and 6-month follow-up).",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # METHODS — Data collection and measurement (5)
    # ================================================================
    {
        "section": "methods", "function_tag": "data_collection",
        "sub_function": "measurement_instrument",
        "template_text": "{variable} was assessed using the {instrument} ({citation}), a validated {scale_type} with demonstrated {property} (Cronbach's α = {alpha}).",
        "slots": {"variable": {"type": "text", "required": True, "hint": "what was measured"},
                  "instrument": {"type": "text", "required": True, "hint": "name of instrument"},
                  "citation": {"type": "text", "required": True, "hint": "author reference for the instrument"},
                  "scale_type": {"type": "select", "required": True, "options": ["self-report questionnaire", "clinical interview", "behavioral task", "physiological measure"]},
                  "property": {"type": "text", "required": True, "hint": "psychometric property (e.g., internal consistency)"},
                  "alpha": {"type": "number", "required": False, "hint": "Cronbach's alpha"}},
        "example_filled": "Depression severity was assessed using the Beck Depression Inventory-II (Beck et al., 1996), a validated self-report questionnaire with demonstrated internal consistency (Cronbach's α = 0.91).",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "data_collection",
        "sub_function": "measurement_instrument",
        "template_text": "All items were rated on a {scale_type} scale ranging from {min} ({min_label}) to {max} ({max_label}).",
        "slots": {"scale_type": {"type": "select", "required": True, "options": ["5-point Likert", "7-point Likert", "10-point visual analog"]},
                  "min": {"type": "number", "required": True, "hint": "minimum scale value"},
                  "min_label": {"type": "text", "required": True, "hint": "what the minimum represents"},
                  "max": {"type": "number", "required": True, "hint": "maximum scale value"},
                  "max_label": {"type": "text", "required": True, "hint": "what the maximum represents"}},
        "example_filled": "All items were rated on a 5-point Likert scale ranging from 1 (strongly disagree) to 5 (strongly agree).",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "data_collection",
        "sub_function": "data_source",
        "template_text": "Data were obtained from {source}, which provides {description} for the period {time_period}.",
        "slots": {"source": {"type": "text", "required": True, "hint": "data source (database, survey, organization)"},
                  "description": {"type": "text", "required": True, "hint": "what the data contains"},
                  "time_period": {"type": "text", "required": True, "hint": "time period covered"}},
        "example_filled": "Data were obtained from the China Health and Retirement Longitudinal Study (CHARLS), which provides nationally representative panel data for the period 2011-2020.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "data_collection",
        "sub_function": "procedure_timeline",
        "template_text": "The study comprised {number} phases: {phase_descriptions}. Each phase lasted approximately {duration_per_phase}.",
        "slots": {"number": {"type": "select", "required": True, "options": ["two", "three", "four"]},
                  "phase_descriptions": {"type": "text", "required": True, "hint": "briefly describe each phase separated by commas"},
                  "duration_per_phase": {"type": "text", "required": True, "hint": "time per phase"}},
        "example_filled": "The study comprised three phases: baseline assessment, intervention delivery, and follow-up evaluation. Each phase lasted approximately 4 weeks.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "data_collection",
        "sub_function": "variable_operationalization",
        "template_text": "The independent variable, {iv_name}, was operationalized as {iv_definition}. The dependent variable, {dv_name}, was operationalized as {dv_definition}.",
        "slots": {"iv_name": {"type": "text", "required": True, "hint": "independent variable name"},
                  "iv_definition": {"type": "text", "required": True, "hint": "how IV is measured/computed"},
                  "dv_name": {"type": "text", "required": True, "hint": "dependent variable name"},
                  "dv_definition": {"type": "text", "required": True, "hint": "how DV is measured/computed"}},
        "example_filled": "The independent variable, work hours, was operationalized as the total self-reported hours worked per week. The dependent variable, burnout, was operationalized as the composite score on the Maslach Burnout Inventory.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # METHODS — Statistical analysis (5)
    # ================================================================
    {
        "section": "methods", "function_tag": "statistical_analysis",
        "sub_function": "general_approach",
        "template_text": "All statistical analyses were conducted using {software} (version {version}). A {threshold}-tailed significance level of α = {alpha} was applied throughout.",
        "slots": {"software": {"type": "select", "required": True, "options": ["SPSS", "R", "Stata", "SAS", "Python"]},
                  "version": {"type": "text", "required": True, "hint": "software version"},
                  "threshold": {"type": "select", "required": True, "options": ["two", "one"]},
                  "alpha": {"type": "number", "required": True, "hint": "significance level"}},
        "example_filled": "All statistical analyses were conducted using R (version 4.3.1). A two-tailed significance level of α = 0.05 was applied throughout.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "statistical_analysis",
        "sub_function": "specific_test",
        "template_text": "{comparison_type} were compared using {test_type}, with {adjustment} correction for multiple comparisons where appropriate.",
        "slots": {"comparison_type": {"type": "text", "required": True, "hint": "what is being compared"},
                  "test_type": {"type": "select", "required": True, "options": ["independent t-tests", "paired t-tests", "one-way ANOVA", "repeated measures ANOVA", "chi-square tests", "Mann-Whitney U tests"]},
                  "adjustment": {"type": "select", "required": True, "options": ["Bonferroni", "Holm-Bonferroni", "Benjamini-Hochberg", "Tukey's HSD"]}},
        "example_filled": "Group means were compared using one-way ANOVA, with Bonferroni correction for multiple comparisons where appropriate.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "statistical_analysis",
        "sub_function": "regression_model",
        "template_text": "A {model_type} was fitted to examine the {relationship} between {predictors} and {outcome}, with {covariates} included as covariates.",
        "slots": {"model_type": {"type": "select", "required": True, "options": ["multiple linear regression", "logistic regression", "hierarchical linear model", "Cox proportional hazards model", "structural equation model"]},
                  "relationship": {"type": "text", "required": True, "hint": "type of relationship being tested"},
                  "predictors": {"type": "text", "required": True, "hint": "predictor variable(s)"},
                  "outcome": {"type": "text", "required": True, "hint": "outcome variable"},
                  "covariates": {"type": "text", "required": True, "hint": "control variables"}},
        "example_filled": "A multiple linear regression was fitted to examine the association between workplace stressors and burnout scores, with age, gender, and years of experience included as covariates.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "statistical_analysis",
        "sub_function": "assumption_checking",
        "template_text": "Prior to analysis, data were screened for {issues}. {check_description}. Where assumptions were violated, {remedy} was applied.",
        "slots": {"issues": {"type": "text", "required": True, "hint": "what was checked (e.g., normality, outliers, multicollinearity)"},
                  "check_description": {"type": "text", "required": True, "hint": "how checks were performed"},
                  "remedy": {"type": "select", "required": True, "options": ["a robust alternative", "bootstrapping", "a non-parametric equivalent", "log-transformation", "Winsorizing of extreme values"]}},
        "example_filled": "Prior to analysis, data were screened for normality and outliers. Normality was assessed using Shapiro-Wilk tests and Q-Q plots. Where assumptions were violated, bootstrapping was applied.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "methods", "function_tag": "statistical_analysis",
        "sub_function": "effect_size",
        "template_text": "Effect sizes were calculated using {effect_size_metric} and interpreted according to {guidelines}'s benchmarks: {thresholds}.",
        "slots": {"effect_size_metric": {"type": "select", "required": True, "options": ["Cohen's d", "partial eta-squared (η²p)", "Cramer's V", "odds ratios"]},
                  "guidelines": {"type": "select", "required": True, "options": ["Cohen (1988)", "Ferguson (2009)", "Sawilowsky (2009)"]},
                  "thresholds": {"type": "text", "required": True, "hint": "specific threshold values"}},
        "example_filled": "Effect sizes were calculated using Cohen's d and interpreted according to Cohen (1988)'s benchmarks: small = 0.2, medium = 0.5, large = 0.8.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # RESULTS — Describing findings (9)
    # ================================================================
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "significant_result",
        "template_text": "A significant {direction} in {variable} was observed between {group_a} (M = {mean_a}, SD = {sd_a}) and {group_b} (M = {mean_b}, SD = {sd_b}), {test_stat} = {value}, p {comparator} {p_value}.",
        "slots": {"direction": {"type": "select", "required": True, "options": ["increase", "decrease", "difference"]},
                  "variable": {"type": "text", "required": True, "hint": "measured variable"},
                  "group_a": {"type": "text", "required": True, "hint": "first group name"},
                  "mean_a": {"type": "number", "required": True, "hint": "mean of group A"},
                  "sd_a": {"type": "number", "required": True, "hint": "SD of group A"},
                  "group_b": {"type": "text", "required": True, "hint": "second group name"},
                  "mean_b": {"type": "number", "required": True, "hint": "mean of group B"},
                  "sd_b": {"type": "number", "required": True, "hint": "SD of group B"},
                  "test_stat": {"type": "select", "required": True, "options": ["t({df})", "F({df1},{df2})", "χ²({df})", "U"]},
                  "value": {"type": "number", "required": True, "hint": "test statistic value"},
                  "comparator": {"type": "select", "required": True, "options": ["<", "=", ">"]},
                  "p_value": {"type": "number", "required": True, "hint": "p-value"}},
        "example_filled": "A significant increase in reaction time was observed between the sleep-deprived group (M = 345.2, SD = 42.3) and the control group (M = 287.6, SD = 35.1), t(40) = 4.87, p < 0.001.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "non_significant_result",
        "template_text": "No significant difference in {variable} was found between {group_a} and {group_b}, {test_stat} = {value}, p = {p_value}.",
        "slots": {"variable": {"type": "text", "required": True, "hint": "measured variable"},
                  "group_a": {"type": "text", "required": True, "hint": "first group"},
                  "group_b": {"type": "text", "required": True, "hint": "second group"},
                  "test_stat": {"type": "select", "required": True, "options": ["t({df})", "F({df1},{df2})", "χ²({df})"]},
                  "value": {"type": "number", "required": True, "hint": "test statistic"},
                  "p_value": {"type": "number", "required": True, "hint": "p-value"}},
        "example_filled": "No significant difference in baseline anxiety scores was found between the treatment group and the control group, t(58) = 0.67, p = 0.51.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "correlation",
        "template_text": "A {strength} {direction} correlation was observed between {variable_a} and {variable_b}, r({df}) = {r_value}, p {comparator} {p_value}.",
        "slots": {"strength": {"type": "select", "required": True, "options": ["strong", "moderate", "weak"]},
                  "direction": {"type": "select", "required": True, "options": ["positive", "negative"]},
                  "variable_a": {"type": "text", "required": True, "hint": "first variable"},
                  "variable_b": {"type": "text", "required": True, "hint": "second variable"},
                  "df": {"type": "number", "required": True, "hint": "degrees of freedom"},
                  "r_value": {"type": "number", "required": True, "hint": "correlation coefficient"},
                  "comparator": {"type": "select", "required": True, "options": ["<", "=", ">"]},
                  "p_value": {"type": "number", "required": True, "hint": "p-value"}},
        "example_filled": "A strong positive correlation was observed between physical activity levels and self-reported well-being, r(198) = 0.62, p < 0.001.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "regression_result",
        "template_text": "{predictor} significantly predicted {outcome} (β = {beta}, SE = {se}, t = {t_value}, p {comparator} {p_value}), accounting for {variance}% of the variance (R² = {r2}).",
        "slots": {"predictor": {"type": "text", "required": True, "hint": "predictor variable"},
                  "outcome": {"type": "text", "required": True, "hint": "outcome variable"},
                  "beta": {"type": "number", "required": True, "hint": "standardized beta coefficient"},
                  "se": {"type": "number", "required": True, "hint": "standard error"},
                  "t_value": {"type": "number", "required": True, "hint": "t-statistic"},
                  "comparator": {"type": "select", "required": True, "options": ["<", "=", ">"]},
                  "p_value": {"type": "number", "required": True, "hint": "p-value"},
                  "variance": {"type": "number", "required": True, "hint": "% variance explained"},
                  "r2": {"type": "number", "required": True, "hint": "R-squared value"}},
        "example_filled": "Job satisfaction significantly predicted turnover intention (β = -0.42, SE = 0.08, t = -5.25, p < 0.001), accounting for 18% of the variance (R² = 0.18).",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "mediation_result",
        "template_text": "The indirect effect of {iv} on {dv} through {mediator} was {significance}, {effect_type} = {effect_value}, 95% CI [{ci_lower}, {ci_upper}].",
        "slots": {"iv": {"type": "text", "required": True, "hint": "independent variable"},
                  "dv": {"type": "text", "required": True, "hint": "dependent variable"},
                  "mediator": {"type": "text", "required": True, "hint": "mediating variable"},
                  "significance": {"type": "select", "required": True, "options": ["significant", "not significant", "marginally significant"]},
                  "effect_type": {"type": "select", "required": True, "options": ["ab", "indirect effect"]},
                  "effect_value": {"type": "number", "required": True, "hint": "effect size"},
                  "ci_lower": {"type": "number", "required": True, "hint": "lower bound of CI"},
                  "ci_upper": {"type": "number", "required": True, "hint": "upper bound of CI"}},
        "example_filled": "The indirect effect of work stress on physical health through sleep quality was significant, indirect effect = -0.23, 95% CI [-0.38, -0.11].",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "moderation_result",
        "template_text": "The interaction between {predictor} and {moderator} was {significance} (β = {beta}, p {comparator} {p_value}), indicating that {interpretation}.",
        "slots": {"predictor": {"type": "text", "required": True, "hint": "main predictor"},
                  "moderator": {"type": "text", "required": True, "hint": "moderator variable"},
                  "significance": {"type": "select", "required": True, "options": ["significant", "not significant"]},
                  "beta": {"type": "number", "required": True, "hint": "interaction beta coefficient"},
                  "comparator": {"type": "select", "required": True, "options": ["<", "=", ">"]},
                  "p_value": {"type": "number", "required": True, "hint": "p-value"},
                  "interpretation": {"type": "text", "required": True, "hint": "what the interaction means"}},
        "example_filled": "The interaction between workload and autonomy was significant (β = -0.15, p = 0.008), indicating that higher autonomy buffered the negative effect of workload on job satisfaction.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "trend_description",
        "template_text": "As shown in Table {table_number}, {variable} {trend_direction} from {baseline_value} at baseline to {followup_value} at follow-up.",
        "slots": {"table_number": {"type": "number", "required": True, "hint": "table number"},
                  "variable": {"type": "text", "required": True, "hint": "variable name"},
                  "trend_direction": {"type": "select", "required": True, "options": ["increased steadily", "decreased markedly", "remained stable", "showed a curvilinear pattern"]},
                  "baseline_value": {"type": "text", "required": True, "hint": "baseline value with units"},
                  "followup_value": {"type": "text", "required": True, "hint": "follow-up value with units"}},
        "example_filled": "As shown in Table 3, systolic blood pressure decreased markedly from 142.3 mmHg at baseline to 128.7 mmHg at the 12-month follow-up.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "descriptive_summary",
        "template_text": "Descriptive statistics for all study variables are presented in Table {table_number}. Overall, {summary_observation}.",
        "slots": {"table_number": {"type": "number", "required": True, "hint": "table number"},
                  "summary_observation": {"type": "text", "required": True, "hint": "high-level observation about the data"}},
        "example_filled": "Descriptive statistics for all study variables are presented in Table 1. Overall, participants reported moderate levels of stress (M = 3.2, SD = 0.9) and relatively high levels of social support (M = 4.1, SD = 0.7).",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "describing_findings",
        "sub_function": "longitudinal_change",
        "template_text": "Repeated measures ANOVA revealed a significant {effect_type} of {factor}, {test_stat} = {value}, p {comparator} {p_value}, η²p = {eta_squared}.",
        "slots": {"effect_type": {"type": "select", "required": True, "options": ["main effect", "interaction effect", "within-subjects effect", "between-subjects effect"]},
                  "factor": {"type": "select", "required": True, "options": ["time", "group", "time × group", "condition"]},
                  "test_stat": {"type": "text", "required": True, "hint": "e.g., F(2, 120)"},
                  "value": {"type": "number", "required": True, "hint": "test statistic value"},
                  "comparator": {"type": "select", "required": True, "options": ["<", "=", ">"]},
                  "p_value": {"type": "number", "required": True, "hint": "p-value"},
                  "eta_squared": {"type": "number", "required": True, "hint": "partial eta-squared"}},
        "example_filled": "Repeated measures ANOVA revealed a significant main effect of time, F(2, 120) = 18.43, p < 0.001, η²p = 0.24.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # RESULTS — Referring to figures and tables (4)
    # ================================================================
    {
        "section": "results", "function_tag": "referring_to_displays",
        "sub_function": "figure_reference",
        "template_text": "As shown in Figure {figure_number}, {description_of_pattern}.",
        "slots": {"figure_number": {"type": "number", "required": True, "hint": "figure number"},
                  "description_of_pattern": {"type": "text", "required": True, "hint": "what the figure shows"}},
        "example_filled": "As shown in Figure 2, reaction times increased linearly with sleep deprivation duration across all participant groups.",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "referring_to_displays",
        "sub_function": "table_reference",
        "template_text": "Table {table_number} summarizes the {content_type} for {groups_or_conditions}.",
        "slots": {"table_number": {"type": "number", "required": True, "hint": "table number"},
                  "content_type": {"type": "select", "required": True, "options": ["descriptive statistics", "regression results", "baseline characteristics", "outcome measures", "correlation matrix"]},
                  "groups_or_conditions": {"type": "text", "required": True, "hint": "what groups/conditions are shown"}},
        "example_filled": "Table 1 summarizes the baseline characteristics for the treatment and control groups.",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "referring_to_displays",
        "sub_function": "figure_comparison",
        "template_text": "Figure {figure_number} compares {what_is_compared} across {dimensions}. Notably, {key_insight}.",
        "slots": {"figure_number": {"type": "number", "required": True, "hint": "figure number"},
                  "what_is_compared": {"type": "text", "required": True, "hint": "what is being compared"},
                  "dimensions": {"type": "text", "required": True, "hint": "what dimensions (groups/time/etc.)"},
                  "key_insight": {"type": "text", "required": True, "hint": "the most notable pattern"}},
        "example_filled": "Figure 3 compares the distribution of scores across all four experimental conditions. Notably, the high-intensity condition showed a bimodal distribution, suggesting the presence of two distinct responder subgroups.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "results", "function_tag": "referring_to_displays",
        "sub_function": "supplementary_reference",
        "template_text": "Detailed {content_type} are provided in the Supplementary Materials (Table S{table_number}).",
        "slots": {"content_type": {"type": "select", "required": True, "options": ["sensitivity analyses", "subgroup analyses", "full model specifications", "additional descriptives"]},
                  "table_number": {"type": "number", "required": True, "hint": "supplementary table number"}},
        "example_filled": "Detailed sensitivity analyses are provided in the Supplementary Materials (Table S1).",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # DISCUSSION — Interpreting results (6)
    # ================================================================
    {
        "section": "discussion", "function_tag": "interpreting_results",
        "sub_function": "supporting_hypothesis",
        "template_text": "These findings are consistent with our hypothesis that {hypothesis_restatement}, suggesting that {interpretation}.",
        "slots": {"hypothesis_restatement": {"type": "text", "required": True, "hint": "restate your hypothesis"},
                  "interpretation": {"type": "text", "required": True, "hint": "what the results mean"}},
        "example_filled": "These findings are consistent with our hypothesis that sleep quality mediates the relationship between screen time and academic performance, suggesting that interventions targeting sleep hygiene may be particularly effective.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "interpreting_results",
        "sub_function": "unexpected_result",
        "template_text": "Contrary to expectations, we found that {unexpected_finding}. A possible explanation for this is that {tentative_explanation}.",
        "slots": {"unexpected_finding": {"type": "text", "required": True, "hint": "what was unexpected"},
                  "tentative_explanation": {"type": "text", "required": True, "hint": "why this might be"}},
        "example_filled": "Contrary to expectations, we found that higher social media use was associated with lower reported loneliness. A possible explanation for this is that online interactions supplement rather than replace face-to-face social contact.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "interpreting_results",
        "sub_function": "explaining_mechanism",
        "template_text": "The observed {phenomenon} may be attributable to {mechanism}. Specifically, it is plausible that {causal_chain}.",
        "slots": {"phenomenon": {"type": "text", "required": True, "hint": "the finding you're explaining"},
                  "mechanism": {"type": "text", "required": True, "hint": "the proposed mechanism"},
                  "causal_chain": {"type": "text", "required": True, "hint": "how the mechanism works step by step"}},
        "example_filled": "The observed reduction in anxiety following the intervention may be attributable to increased prefrontal regulation of amygdala reactivity. Specifically, it is plausible that mindfulness training strengthens top-down control pathways.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "interpreting_results",
        "sub_function": "magnitude_assessment",
        "template_text": "The magnitude of the observed effect ({effect_size}) is {comparison} previously reported values in the literature ({range_from_literature}), suggesting that {implication}.",
        "slots": {"effect_size": {"type": "text", "required": True, "hint": "your effect size with CI"},
                  "comparison": {"type": "select", "required": True, "options": ["larger than", "comparable to", "smaller than"]},
                  "range_from_literature": {"type": "text", "required": True, "hint": "typical range from literature"},
                  "implication": {"type": "text", "required": True, "hint": "what this means"}},
        "example_filled": "The magnitude of the observed effect (d = 0.72, 95% CI [0.48, 0.96]) is larger than previously reported values in the literature (range: d = 0.2-0.5), suggesting that the enhanced intervention protocol may offer meaningful clinical advantages.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "interpreting_results",
        "sub_function": "null_result_interpretation",
        "template_text": "The absence of a significant effect for {variable} does not necessarily imply that {variable} is unimportant. Rather, it may reflect {alternative_explanation}.",
        "slots": {"variable": {"type": "text", "required": True, "hint": "the variable with null result"},
                  "alternative_explanation": {"type": "text", "required": True, "hint": "why this might be a null finding (power, measurement, etc.)"}},
        "example_filled": "The absence of a significant effect for gender does not necessarily imply that gender is unimportant. Rather, it may reflect insufficient statistical power to detect a small interaction effect given the unequal gender distribution in our sample.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "interpreting_results",
        "sub_function": "key_finding_summary",
        "template_text": "Taken together, our results indicate that {overall_conclusion}. This pattern of findings extends prior work by demonstrating that {extension}.",
        "slots": {"overall_conclusion": {"type": "text", "required": True, "hint": "overall takeaway"},
                  "extension": {"type": "text", "required": True, "hint": "how this extends previous knowledge"}},
        "example_filled": "Taken together, our results indicate that personality traits influence health behaviors primarily through social-cognitive pathways rather than direct dispositional effects. This pattern of findings extends prior work by demonstrating that the mediation pathway is moderated by cultural context.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # DISCUSSION — Comparing with literature (6)
    # ================================================================
    {
        "section": "discussion", "function_tag": "comparing_literature",
        "sub_function": "consistent_with",
        "template_text": "Our finding that {finding_summary} aligns with previous work by {author_citation}, who reported that {previous_finding}.",
        "slots": {"finding_summary": {"type": "text", "required": True, "hint": "your key finding"},
                  "author_citation": {"type": "text", "required": True, "hint": "author name and year"},
                  "previous_finding": {"type": "text", "required": True, "hint": "what they found"}},
        "example_filled": "Our finding that mindfulness training reduced cortisol levels aligns with previous work by Davidson et al. (2003), who reported that an 8-week mindfulness program significantly decreased stress hormone production.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "comparing_literature",
        "sub_function": "contrasting_with",
        "template_text": "In contrast to {author_citation}, who found {previous_finding}, our data suggest that {different_finding}. This discrepancy may be attributable to {potential_reason}.",
        "slots": {"author_citation": {"type": "text", "required": True, "hint": "author and year"},
                  "previous_finding": {"type": "text", "required": True, "hint": "what they found"},
                  "different_finding": {"type": "text", "required": True, "hint": "what you found differently"},
                  "potential_reason": {"type": "text", "required": True, "hint": "possible reason for difference"}},
        "example_filled": "In contrast to Smith et al. (2022), who found that remote work decreased productivity, our data suggest that hybrid work arrangements improved measured output. This discrepancy may be attributable to differences in industry sector and job role composition.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "comparing_literature",
        "sub_function": "extending_work",
        "template_text": "While {author_citation} demonstrated that {prior_knowledge}, our study extends this work by showing that {extension}.",
        "slots": {"author_citation": {"type": "text", "required": True, "hint": "author and year"},
                  "prior_knowledge": {"type": "text", "required": True, "hint": "what was already known"},
                  "extension": {"type": "text", "required": True, "hint": "what your study adds"}},
        "example_filled": "While Chen et al. (2021) demonstrated that cognitive behavioral therapy is effective for treating depression in primary care settings, our study extends this work by showing that a self-guided digital version yields comparable outcomes at a fraction of the cost.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "comparing_literature",
        "sub_function": "meta_analysis_comparison",
        "template_text": "The effect size observed in our study ({observed_es}) falls within the {percentile} percentile of effects reported in {meta_citation}'s meta-analysis of {num_studies} studies.",
        "slots": {"observed_es": {"type": "text", "required": True, "hint": "your observed effect size"},
                  "percentile": {"type": "select", "required": True, "options": ["75th", "50th", "90th", "25th"]},
                  "meta_citation": {"type": "text", "required": True, "hint": "meta-analysis author"},
                  "num_studies": {"type": "number", "required": True, "hint": "number of studies in the meta-analysis"}},
        "example_filled": "The effect size observed in our study (d = 0.72) falls within the 90th percentile of effects reported in Johnson et al.'s (2023) meta-analysis of 87 studies.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "comparing_literature",
        "sub_function": "reconciling_differences",
        "template_text": "Taken together with {author_a} and {author_b}, a coherent picture begins to emerge: {synthesis}.",
        "slots": {"author_a": {"type": "text", "required": True, "hint": "first study"},
                  "author_b": {"type": "text", "required": True, "hint": "second study"},
                  "synthesis": {"type": "text", "required": True, "hint": "what these studies tell us together"}},
        "example_filled": "Taken together with Lee et al. (2022) and Park et al. (2023), a coherent picture begins to emerge: digital interventions are most effective when they include human support components, regardless of the underlying therapeutic modality.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "comparing_literature",
        "sub_function": "identifying_pattern",
        "template_text": "Consistent with a growing body of evidence ({citations}), our results support the view that {theoretical_statement}.",
        "slots": {"citations": {"type": "text", "required": True, "hint": "multiple citations, e.g., 'Author A, 2020; Author B, 2021'"},
                  "theoretical_statement": {"type": "text", "required": True, "hint": "the theoretical claim supported"}},
        "example_filled": "Consistent with a growing body of evidence (Zhang, 2020; Kim et al., 2021; Müller & Schmidt, 2022), our results support the view that bilingualism confers domain-general cognitive advantages rather than language-specific benefits alone.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # DISCUSSION — Acknowledging limitations (5)
    # ================================================================
    {
        "section": "discussion", "function_tag": "acknowledging_limitations",
        "sub_function": "generalizability",
        "template_text": "Several limitations of this study should be noted. First, {limitation_a}. Second, {limitation_b}. These factors may limit the generalizability of our findings to {broader_context}.",
        "slots": {"limitation_a": {"type": "text", "required": True, "hint": "first limitation"},
                  "limitation_b": {"type": "text", "required": True, "hint": "second limitation"},
                  "broader_context": {"type": "text", "required": True, "hint": "what population/context this may not apply to"}},
        "example_filled": "Several limitations of this study should be noted. First, the sample was predominantly drawn from a single geographic region. Second, the cross-sectional design precludes causal inference. These factors may limit the generalizability of our findings to more diverse populations.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "acknowledging_limitations",
        "sub_function": "methodological",
        "template_text": "A methodological limitation is that {method_issue}. Future studies should consider {improvement_suggestion}.",
        "slots": {"method_issue": {"type": "text", "required": True, "hint": "what methodological issue exists"},
                  "improvement_suggestion": {"type": "text", "required": True, "hint": "how to improve"}},
        "example_filled": "A methodological limitation is that all outcome measures were self-reported, which may introduce recall bias. Future studies should consider incorporating objective measures such as actigraphy or biomarker validation.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "acknowledging_limitations",
        "sub_function": "sample_limitation",
        "template_text": "The relatively {sample_characteristic} nature of our sample (N = {n}) may limit statistical power to detect {type_of_effect} effects. Larger-scale studies are needed to {purpose}.",
        "slots": {"sample_characteristic": {"type": "select", "required": True, "options": ["small", "homogeneous", "convenience-based", "self-selected"]},
                  "n": {"type": "number", "required": True, "hint": "sample size"},
                  "type_of_effect": {"type": "select", "required": True, "options": ["small-to-medium", "interaction", "moderation", "subgroup"]},
                  "purpose": {"type": "text", "required": True, "hint": "what larger studies should achieve"}},
        "example_filled": "The relatively homogeneous nature of our sample (N = 85) may limit statistical power to detect interaction effects. Larger-scale studies with more diverse samples are needed to examine potential moderators.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "acknowledging_limitations",
        "sub_function": "measurement_limitation",
        "template_text": "We acknowledge that our operationalization of {construct} using {measure} captures only {aspect} of this multifaceted construct. Alternative measures such as {alternative} may yield different results.",
        "slots": {"construct": {"type": "text", "required": True, "hint": "the construct being measured"},
                  "measure": {"type": "text", "required": True, "hint": "measurement instrument used"},
                  "aspect": {"type": "text", "required": True, "hint": "which aspect is captured"},
                  "alternative": {"type": "text", "required": True, "hint": "alternative measurement approaches"}},
        "example_filled": "We acknowledge that our operationalization of emotional intelligence using a self-report scale captures only the trait aspect of this multifaceted construct. Alternative measures such as ability-based tests may yield different results.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "acknowledging_limitations",
        "sub_function": "balanced_view",
        "template_text": "Despite these limitations, our study has several strengths, including {strength_a} and {strength_b}, which enhance {quality_aspect}.",
        "slots": {"strength_a": {"type": "text", "required": True, "hint": "first strength"},
                  "strength_b": {"type": "text", "required": True, "hint": "second strength"},
                  "quality_aspect": {"type": "select", "required": True, "options": ["internal validity", "ecological validity", "generalizability", "statistical power", "measurement precision"]}},
        "example_filled": "Despite these limitations, our study has several strengths, including the use of a longitudinal design and multi-source data collection, which enhance internal validity.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # DISCUSSION — Implications (6)
    # ================================================================
    {
        "section": "discussion", "function_tag": "implications",
        "sub_function": "practical_implications",
        "template_text": "From a practical standpoint, these results suggest that {recommendation}. {stakeholder} should consider {action} when {context}.",
        "slots": {"recommendation": {"type": "text", "required": True, "hint": "what should be done"},
                  "stakeholder": {"type": "text", "required": True, "hint": "who (e.g., clinicians, educators)"},
                  "action": {"type": "text", "required": True, "hint": "specific action"},
                  "context": {"type": "text", "required": True, "hint": "when/where this applies"}},
        "example_filled": "From a practical standpoint, these results suggest that workplace wellness programs should include sleep hygiene education. HR managers should consider offering flexible schedules when employees are recovering from night shift rotations.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "implications",
        "sub_function": "future_research",
        "template_text": "Future research should examine whether {extension_question} using {suggested_method} in a {population} population.",
        "slots": {"extension_question": {"type": "text", "required": True, "hint": "what question remains"},
                  "suggested_method": {"type": "select", "required": True, "options": ["a longitudinal design", "a randomized controlled trial", "qualitative methods", "a larger sample", "multi-site data collection"]},
                  "population": {"type": "text", "required": True, "hint": "which population"}},
        "example_filled": "Future research should examine whether the observed effects persist beyond 12 months using a longitudinal design in a more ethnically diverse population.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "implications",
        "sub_function": "theoretical_implications",
        "template_text": "These findings contribute to {theoretical_framework} by demonstrating that {theoretical_insight}. This suggests that {framework_modification} may be warranted.",
        "slots": {"theoretical_framework": {"type": "text", "required": True, "hint": "the theoretical framework"},
                  "theoretical_insight": {"type": "text", "required": True, "hint": "what this study reveals about the theory"},
                  "framework_modification": {"type": "text", "required": True, "hint": "how the theory should be updated"}},
        "example_filled": "These findings contribute to Self-Determination Theory by demonstrating that autonomy support is particularly important in collectivist cultural contexts. This suggests that a contextual modification of the theory may be warranted.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "implications",
        "sub_function": "policy_implications",
        "template_text": "At a policy level, our findings underscore the need for {policy_action}. Specifically, policymakers should {specific_action} in order to {desired_outcome}.",
        "slots": {"policy_action": {"type": "text", "required": True, "hint": "what policy change is needed"},
                  "specific_action": {"type": "text", "required": True, "hint": "specific policy action"},
                  "desired_outcome": {"type": "text", "required": True, "hint": "intended result"}},
        "example_filled": "At a policy level, our findings underscore the need for mandatory mental health screening in primary care. Specifically, policymakers should integrate brief validated screening tools into routine check-ups in order to identify at-risk individuals earlier.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "implications",
        "sub_function": "specific_future_direction",
        "template_text": "An important next step would be to {research_action} in order to {goal}. Additionally, {second_direction} would help establish {purpose}.",
        "slots": {"research_action": {"type": "text", "required": True, "hint": "specific research action"},
                  "goal": {"type": "text", "required": True, "hint": "what this would achieve"},
                  "second_direction": {"type": "text", "required": True, "hint": "second future direction"},
                  "purpose": {"type": "text", "required": True, "hint": "what this would establish"}},
        "example_filled": "An important next step would be to conduct a fully-powered RCT in order to establish causal efficacy. Additionally, mediation analyses would help establish the precise mechanisms through which the intervention operates.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "discussion", "function_tag": "implications",
        "sub_function": "translational_statement",
        "template_text": "The translational potential of these findings is {assessment}. With further validation, {application} could be implemented in {setting} settings.",
        "slots": {"assessment": {"type": "select", "required": True, "options": ["promising", "substantial", "limited at this stage"]},
                  "application": {"type": "text", "required": True, "hint": "what could be implemented"},
                  "setting": {"type": "text", "required": True, "hint": "where it could be implemented"}},
        "example_filled": "The translational potential of these findings is promising. With further validation, the digital screening protocol could be implemented in routine primary care settings.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },

    # ================================================================
    # CONCLUSION — Summarizing and future work (8)
    # ================================================================
    {
        "section": "conclusion", "function_tag": "summarizing_findings",
        "sub_function": "key_findings",
        "template_text": "In conclusion, this {study_type} demonstrates that {main_finding}. These findings contribute to our understanding of {broader_topic} by showing that {contribution}.",
        "slots": {"study_type": {"type": "select", "required": True, "options": ["study", "investigation", "randomized controlled trial", "systematic review", "meta-analysis"]},
                  "main_finding": {"type": "text", "required": True, "hint": "main finding"},
                  "broader_topic": {"type": "text", "required": True, "hint": "broader topic area"},
                  "contribution": {"type": "text", "required": True, "hint": "what this adds to knowledge"}},
        "example_filled": "In conclusion, this study demonstrates that a brief mindfulness intervention significantly reduces anxiety symptoms among university students. These findings contribute to our understanding of accessible mental health interventions.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "conclusion", "function_tag": "summarizing_findings",
        "sub_function": "contribution_statement",
        "template_text": "This work makes {number} key contributions to the {field} literature: ({contribution_a}) {description_a}, and ({contribution_b}) {description_b}.",
        "slots": {"number": {"type": "select", "required": True, "options": ["two", "three"]},
                  "field": {"type": "text", "required": True, "hint": "your field"},
                  "contribution_a": {"type": "text", "required": True, "hint": "label for first contribution"},
                  "description_a": {"type": "text", "required": True, "hint": "description of first contribution"},
                  "contribution_b": {"type": "text", "required": True, "hint": "label for second contribution"},
                  "description_b": {"type": "text", "required": True, "hint": "description of second contribution"}},
        "example_filled": "This work makes two key contributions to the cognitive neuroscience literature: (i) methodological — a validated paradigm for assessing working memory, and (ii) empirical — evidence that domain-general executive resources constrain multi-tasking performance.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "conclusion", "function_tag": "summarizing_findings",
        "sub_function": "practical_value",
        "template_text": "Beyond its theoretical contributions, this research offers practical value for {stakeholder} seeking to {goal}.",
        "slots": {"stakeholder": {"type": "text", "required": True, "hint": "who can use this"},
                  "goal": {"type": "text", "required": True, "hint": "what they can achieve"}},
        "example_filled": "Beyond its theoretical contributions, this research offers practical value for hospital administrators seeking to reduce nurse burnout through evidence-based scheduling interventions.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "conclusion", "function_tag": "suggesting_future_work",
        "sub_function": "next_steps",
        "template_text": "Building on these findings, future work should {action_a} and {action_b} to further advance this line of inquiry.",
        "slots": {"action_a": {"type": "text", "required": True, "hint": "first future action"},
                  "action_b": {"type": "text", "required": True, "hint": "second future action"}},
        "example_filled": "Building on these findings, future work should replicate these results in clinical populations and examine long-term maintenance effects to further advance this line of inquiry.",
        "academic_level": "basic", "source": "Manchester Phrasebank",
    },
    {
        "section": "conclusion", "function_tag": "summarizing_findings",
        "sub_function": "take_home_message",
        "template_text": "The central message emerging from this work is that {takeaway}. We hope this finding stimulates further investigation into {future_area}.",
        "slots": {"takeaway": {"type": "text", "required": True, "hint": "the single most important message"},
                  "future_area": {"type": "text", "required": True, "hint": "what future research should explore"}},
        "example_filled": "The central message emerging from this work is that even low-intensity interventions can produce clinically meaningful outcomes when delivered with fidelity. We hope this finding stimulates further investigation into scalable mental health solutions.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "conclusion", "function_tag": "summarizing_findings",
        "sub_function": "closing_statement",
        "template_text": "Ultimately, this research {action} by demonstrating that {insight}, thereby opening new avenues for {future_possibility}.",
        "slots": {"action": {"type": "select", "required": True, "options": ["advances the field", "fills a critical gap", "challenges prevailing assumptions", "provides a foundation"]},
                  "insight": {"type": "text", "required": True, "hint": "key insight"},
                  "future_possibility": {"type": "text", "required": True, "hint": "what becomes possible now"}},
        "example_filled": "Ultimately, this research advances the field by demonstrating that social media data can validly predict population-level mental health trends, thereby opening new avenues for real-time public health surveillance.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
    {
        "section": "conclusion", "function_tag": "summarizing_findings",
        "sub_function": "balanced_conclusion",
        "template_text": "While acknowledging the preliminary nature of these findings, this study provides initial evidence that {finding}. These results lay the groundwork for {future_work}.",
        "slots": {"finding": {"type": "text", "required": True, "hint": "your main finding (cautiously stated)"},
                  "future_work": {"type": "text", "required": True, "hint": "what future work this enables"}},
        "example_filled": "While acknowledging the preliminary nature of these findings, this study provides initial evidence that gamification elements can enhance engagement with digital health interventions. These results lay the groundwork for larger-scale trials.",
        "academic_level": "intermediate", "source": "Manchester Phrasebank",
    },
    {
        "section": "conclusion", "function_tag": "summarizing_findings",
        "sub_function": "broad_impact",
        "template_text": "The implications of this research extend beyond {specific_domain} to inform our understanding of {broader_phenomenon} more generally.",
        "slots": {"specific_domain": {"type": "text", "required": True, "hint": "your specific research domain"},
                  "broader_phenomenon": {"type": "text", "required": True, "hint": "broader phenomenon this speaks to"}},
        "example_filled": "The implications of this research extend beyond consumer behavior in e-commerce to inform our understanding of how trust forms in digital environments more generally.",
        "academic_level": "advanced", "source": "Manchester Phrasebank",
    },
]

# Total: 84 curated phrase templates covering all major SCI sections and functions
